//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pbx_web.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("this is an app setting.")]
        public string testsetting {
            get {
                return ((string)(this["testsetting"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string queue_host {
            get {
                return ((string)(this["queue_host"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("phoneswitchevents")]
        public string queue_name {
            get {
                return ((string)(this["queue_name"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>1234567890,t1</string>
  <string>1234567891,t1</string>
  <string>1234567892,t1</string>
  <string>1234567893,t1</string>
  <string>1234567894,t1</string>
  <string>1234567895,t1</string>
  <string>1234567896,t1</string>
  <string>6175551234,analog</string>
  <string>6175551235,analog</string>
  <string>6175551236,analog</string>
  <string>6175551237,analog</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection trunks {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["trunks"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0000,d,0</string>
  <string>0001,d,1</string>
  <string>0002,d,2</string>
  <string>0003,d,3</string>
  <string>0004,d,4</string>
  <string>0005,d,5</string>
  <string>0006,d,6</string>
  <string>0007,ip,1.1.1.1</string>
  <string>0008,ip,1.1.1.2</string>
  <string>0009,ip,1.1.1.3</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection extensions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["extensions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>localhost,phoneswitchevents</string>
  <string>localhost,pbx_mirror</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection queues {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["queues"]));
            }
        }
    }
}
