//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_pbx_web2.LIVE_adminproxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="phonenumber", Namespace="http://schemas.datacontract.org/2004/07/pbx_shared")]
    [System.SerializableAttribute()]
    public partial class phonenumber : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool activeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string caller_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private test_pbx_web2.LIVE_adminproxy.phonenumber.caller_id_modes caller_id_modeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string caller_id_prefixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private test_pbx_web2.LIVE_adminproxy.call_route_destination default_routeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private test_pbx_web2.LIVE_adminproxy.hold_music_group hold_music_groupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private test_pbx_web2.LIVE_adminproxy.call_route_destination holiday_routeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private test_pbx_web2.LIVE_adminproxy.phonenumber.trunkstates linestateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private test_pbx_web2.LIVE_adminproxy.phonenumber.trunktypes linetypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phonenbrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool screen_for_privacyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool show_callerid_on_outboundField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool active {
            get {
                return this.activeField;
            }
            set {
                if ((this.activeField.Equals(value) != true)) {
                    this.activeField = value;
                    this.RaisePropertyChanged("active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string caller_id {
            get {
                return this.caller_idField;
            }
            set {
                if ((object.ReferenceEquals(this.caller_idField, value) != true)) {
                    this.caller_idField = value;
                    this.RaisePropertyChanged("caller_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public test_pbx_web2.LIVE_adminproxy.phonenumber.caller_id_modes caller_id_mode {
            get {
                return this.caller_id_modeField;
            }
            set {
                if ((this.caller_id_modeField.Equals(value) != true)) {
                    this.caller_id_modeField = value;
                    this.RaisePropertyChanged("caller_id_mode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string caller_id_prefix {
            get {
                return this.caller_id_prefixField;
            }
            set {
                if ((object.ReferenceEquals(this.caller_id_prefixField, value) != true)) {
                    this.caller_id_prefixField = value;
                    this.RaisePropertyChanged("caller_id_prefix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public test_pbx_web2.LIVE_adminproxy.call_route_destination default_route {
            get {
                return this.default_routeField;
            }
            set {
                if ((object.ReferenceEquals(this.default_routeField, value) != true)) {
                    this.default_routeField = value;
                    this.RaisePropertyChanged("default_route");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public test_pbx_web2.LIVE_adminproxy.hold_music_group hold_music_group {
            get {
                return this.hold_music_groupField;
            }
            set {
                if ((object.ReferenceEquals(this.hold_music_groupField, value) != true)) {
                    this.hold_music_groupField = value;
                    this.RaisePropertyChanged("hold_music_group");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public test_pbx_web2.LIVE_adminproxy.call_route_destination holiday_route {
            get {
                return this.holiday_routeField;
            }
            set {
                if ((object.ReferenceEquals(this.holiday_routeField, value) != true)) {
                    this.holiday_routeField = value;
                    this.RaisePropertyChanged("holiday_route");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public test_pbx_web2.LIVE_adminproxy.phonenumber.trunkstates linestate {
            get {
                return this.linestateField;
            }
            set {
                if ((this.linestateField.Equals(value) != true)) {
                    this.linestateField = value;
                    this.RaisePropertyChanged("linestate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public test_pbx_web2.LIVE_adminproxy.phonenumber.trunktypes linetype {
            get {
                return this.linetypeField;
            }
            set {
                if ((this.linetypeField.Equals(value) != true)) {
                    this.linetypeField = value;
                    this.RaisePropertyChanged("linetype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phonenbr {
            get {
                return this.phonenbrField;
            }
            set {
                if ((object.ReferenceEquals(this.phonenbrField, value) != true)) {
                    this.phonenbrField = value;
                    this.RaisePropertyChanged("phonenbr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool screen_for_privacy {
            get {
                return this.screen_for_privacyField;
            }
            set {
                if ((this.screen_for_privacyField.Equals(value) != true)) {
                    this.screen_for_privacyField = value;
                    this.RaisePropertyChanged("screen_for_privacy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool show_callerid_on_outbound {
            get {
                return this.show_callerid_on_outboundField;
            }
            set {
                if ((this.show_callerid_on_outboundField.Equals(value) != true)) {
                    this.show_callerid_on_outboundField = value;
                    this.RaisePropertyChanged("show_callerid_on_outbound");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="phonenumber.caller_id_modes", Namespace="http://schemas.datacontract.org/2004/07/pbx_shared")]
        public enum caller_id_modes : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            none = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            your_text = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            your_text_plus_original = 2,
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="phonenumber.trunkstates", Namespace="http://schemas.datacontract.org/2004/07/pbx_shared")]
        public enum trunkstates : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            idle = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ringing = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            connected = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            cleanup = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            unknown = 4,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            offline = 5,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            hold = 6,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            busy = 7,
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="phonenumber.trunktypes", Namespace="http://schemas.datacontract.org/2004/07/pbx_shared")]
        public enum trunktypes : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            analog = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            t1 = 1,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="call_route_destination", Namespace="http://schemas.datacontract.org/2004/07/pbx_shared")]
    [System.SerializableAttribute()]
    public partial class call_route_destination : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ring_timeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private test_pbx_web2.LIVE_adminproxy.call_route_destination.routable_types route_destination_typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private test_pbx_web2.LIVE_adminproxy.attendant target_attendantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private test_pbx_web2.LIVE_adminproxy.extension target_extensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private test_pbx_web2.LIVE_adminproxy.mailbox target_mailboxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private test_pbx_web2.LIVE_adminproxy.queue target_queueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ring_time {
            get {
                return this.ring_timeField;
            }
            set {
                if ((this.ring_timeField.Equals(value) != true)) {
                    this.ring_timeField = value;
                    this.RaisePropertyChanged("ring_time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public test_pbx_web2.LIVE_adminproxy.call_route_destination.routable_types route_destination_type {
            get {
                return this.route_destination_typeField;
            }
            set {
                if ((this.route_destination_typeField.Equals(value) != true)) {
                    this.route_destination_typeField = value;
                    this.RaisePropertyChanged("route_destination_type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public test_pbx_web2.LIVE_adminproxy.attendant target_attendant {
            get {
                return this.target_attendantField;
            }
            set {
                if ((object.ReferenceEquals(this.target_attendantField, value) != true)) {
                    this.target_attendantField = value;
                    this.RaisePropertyChanged("target_attendant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public test_pbx_web2.LIVE_adminproxy.extension target_extension {
            get {
                return this.target_extensionField;
            }
            set {
                if ((object.ReferenceEquals(this.target_extensionField, value) != true)) {
                    this.target_extensionField = value;
                    this.RaisePropertyChanged("target_extension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public test_pbx_web2.LIVE_adminproxy.mailbox target_mailbox {
            get {
                return this.target_mailboxField;
            }
            set {
                if ((object.ReferenceEquals(this.target_mailboxField, value) != true)) {
                    this.target_mailboxField = value;
                    this.RaisePropertyChanged("target_mailbox");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public test_pbx_web2.LIVE_adminproxy.queue target_queue {
            get {
                return this.target_queueField;
            }
            set {
                if ((object.ReferenceEquals(this.target_queueField, value) != true)) {
                    this.target_queueField = value;
                    this.RaisePropertyChanged("target_queue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="call_route_destination.routable_types", Namespace="http://schemas.datacontract.org/2004/07/pbx_shared")]
        public enum routable_types : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            extension = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            queue = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            attendant = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            mailbox = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            find_me = 4,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="hold_music_group", Namespace="http://schemas.datacontract.org/2004/07/pbx_shared")]
    [System.SerializableAttribute()]
    public partial class hold_music_group : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool shuffle_tracksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool use_for_outboundField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool shuffle_tracks {
            get {
                return this.shuffle_tracksField;
            }
            set {
                if ((this.shuffle_tracksField.Equals(value) != true)) {
                    this.shuffle_tracksField = value;
                    this.RaisePropertyChanged("shuffle_tracks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool use_for_outbound {
            get {
                return this.use_for_outboundField;
            }
            set {
                if ((this.use_for_outboundField.Equals(value) != true)) {
                    this.use_for_outboundField = value;
                    this.RaisePropertyChanged("use_for_outbound");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="attendant", Namespace="http://schemas.datacontract.org/2004/07/pbx_shared")]
    [System.SerializableAttribute()]
    public partial class attendant : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="extension", Namespace="http://schemas.datacontract.org/2004/07/pbx_shared")]
    [System.SerializableAttribute()]
    public partial class extension : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string e911locationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string extension_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string extension_nbrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private test_pbx_web2.LIVE_adminproxy.extension.extension_types extension_typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string outbound_callerid_phonenbrField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string e911location {
            get {
                return this.e911locationField;
            }
            set {
                if ((object.ReferenceEquals(this.e911locationField, value) != true)) {
                    this.e911locationField = value;
                    this.RaisePropertyChanged("e911location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string extension_name {
            get {
                return this.extension_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.extension_nameField, value) != true)) {
                    this.extension_nameField = value;
                    this.RaisePropertyChanged("extension_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string extension_nbr {
            get {
                return this.extension_nbrField;
            }
            set {
                if ((object.ReferenceEquals(this.extension_nbrField, value) != true)) {
                    this.extension_nbrField = value;
                    this.RaisePropertyChanged("extension_nbr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public test_pbx_web2.LIVE_adminproxy.extension.extension_types extension_type {
            get {
                return this.extension_typeField;
            }
            set {
                if ((this.extension_typeField.Equals(value) != true)) {
                    this.extension_typeField = value;
                    this.RaisePropertyChanged("extension_type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string outbound_callerid_phonenbr {
            get {
                return this.outbound_callerid_phonenbrField;
            }
            set {
                if ((object.ReferenceEquals(this.outbound_callerid_phonenbrField, value) != true)) {
                    this.outbound_callerid_phonenbrField = value;
                    this.RaisePropertyChanged("outbound_callerid_phonenbr");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="extension.extension_types", Namespace="http://schemas.datacontract.org/2004/07/pbx_shared")]
        public enum extension_types : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            digital = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ip = 1,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="mailbox", Namespace="http://schemas.datacontract.org/2004/07/pbx_shared")]
    [System.SerializableAttribute()]
    public partial class mailbox : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string greeting_fileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool hide_mailbox_From_directoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mailbox_nbrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool skip_voicemail_instructionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string timezoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private test_pbx_web2.LIVE_adminproxy.mailbox.voicemail_delete_timeframes voicemail_delete_timeframeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string greeting_file {
            get {
                return this.greeting_fileField;
            }
            set {
                if ((object.ReferenceEquals(this.greeting_fileField, value) != true)) {
                    this.greeting_fileField = value;
                    this.RaisePropertyChanged("greeting_file");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool hide_mailbox_From_directory {
            get {
                return this.hide_mailbox_From_directoryField;
            }
            set {
                if ((this.hide_mailbox_From_directoryField.Equals(value) != true)) {
                    this.hide_mailbox_From_directoryField = value;
                    this.RaisePropertyChanged("hide_mailbox_From_directory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mailbox_nbr {
            get {
                return this.mailbox_nbrField;
            }
            set {
                if ((object.ReferenceEquals(this.mailbox_nbrField, value) != true)) {
                    this.mailbox_nbrField = value;
                    this.RaisePropertyChanged("mailbox_nbr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool skip_voicemail_instructions {
            get {
                return this.skip_voicemail_instructionsField;
            }
            set {
                if ((this.skip_voicemail_instructionsField.Equals(value) != true)) {
                    this.skip_voicemail_instructionsField = value;
                    this.RaisePropertyChanged("skip_voicemail_instructions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string timezone {
            get {
                return this.timezoneField;
            }
            set {
                if ((object.ReferenceEquals(this.timezoneField, value) != true)) {
                    this.timezoneField = value;
                    this.RaisePropertyChanged("timezone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public test_pbx_web2.LIVE_adminproxy.mailbox.voicemail_delete_timeframes voicemail_delete_timeframe {
            get {
                return this.voicemail_delete_timeframeField;
            }
            set {
                if ((this.voicemail_delete_timeframeField.Equals(value) != true)) {
                    this.voicemail_delete_timeframeField = value;
                    this.RaisePropertyChanged("voicemail_delete_timeframe");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="mailbox.voicemail_delete_timeframes", Namespace="http://schemas.datacontract.org/2004/07/pbx_shared")]
        public enum voicemail_delete_timeframes : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            never = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            week = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            month = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            year = 3,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="queue", Namespace="http://schemas.datacontract.org/2004/07/pbx_shared")]
    [System.SerializableAttribute()]
    public partial class queue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private test_pbx_web2.LIVE_adminproxy.call_route_destination after_timeoutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private test_pbx_web2.LIVE_adminproxy.queue.agent_removal_actions agent_removal_actionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private test_pbx_web2.LIVE_adminproxy.supportrep[] agentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool announce_hold_timeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool announce_positionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string callerid_prefixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private test_pbx_web2.LIVE_adminproxy.queue.unanswered_actions if_agent_does_not_answerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool joinwhenemptyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool play_periodic_announcementsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int priorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int queue_timeoutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ring_durationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ringinuseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool user_agent_priorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int wrapup_timeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool zero_exits_queueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public test_pbx_web2.LIVE_adminproxy.call_route_destination after_timeout {
            get {
                return this.after_timeoutField;
            }
            set {
                if ((object.ReferenceEquals(this.after_timeoutField, value) != true)) {
                    this.after_timeoutField = value;
                    this.RaisePropertyChanged("after_timeout");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public test_pbx_web2.LIVE_adminproxy.queue.agent_removal_actions agent_removal_action {
            get {
                return this.agent_removal_actionField;
            }
            set {
                if ((this.agent_removal_actionField.Equals(value) != true)) {
                    this.agent_removal_actionField = value;
                    this.RaisePropertyChanged("agent_removal_action");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public test_pbx_web2.LIVE_adminproxy.supportrep[] agents {
            get {
                return this.agentsField;
            }
            set {
                if ((object.ReferenceEquals(this.agentsField, value) != true)) {
                    this.agentsField = value;
                    this.RaisePropertyChanged("agents");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool announce_hold_time {
            get {
                return this.announce_hold_timeField;
            }
            set {
                if ((this.announce_hold_timeField.Equals(value) != true)) {
                    this.announce_hold_timeField = value;
                    this.RaisePropertyChanged("announce_hold_time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool announce_position {
            get {
                return this.announce_positionField;
            }
            set {
                if ((this.announce_positionField.Equals(value) != true)) {
                    this.announce_positionField = value;
                    this.RaisePropertyChanged("announce_position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string callerid_prefix {
            get {
                return this.callerid_prefixField;
            }
            set {
                if ((object.ReferenceEquals(this.callerid_prefixField, value) != true)) {
                    this.callerid_prefixField = value;
                    this.RaisePropertyChanged("callerid_prefix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public test_pbx_web2.LIVE_adminproxy.queue.unanswered_actions if_agent_does_not_answer {
            get {
                return this.if_agent_does_not_answerField;
            }
            set {
                if ((this.if_agent_does_not_answerField.Equals(value) != true)) {
                    this.if_agent_does_not_answerField = value;
                    this.RaisePropertyChanged("if_agent_does_not_answer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool joinwhenempty {
            get {
                return this.joinwhenemptyField;
            }
            set {
                if ((this.joinwhenemptyField.Equals(value) != true)) {
                    this.joinwhenemptyField = value;
                    this.RaisePropertyChanged("joinwhenempty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool play_periodic_announcements {
            get {
                return this.play_periodic_announcementsField;
            }
            set {
                if ((this.play_periodic_announcementsField.Equals(value) != true)) {
                    this.play_periodic_announcementsField = value;
                    this.RaisePropertyChanged("play_periodic_announcements");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int priority {
            get {
                return this.priorityField;
            }
            set {
                if ((this.priorityField.Equals(value) != true)) {
                    this.priorityField = value;
                    this.RaisePropertyChanged("priority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int queue_timeout {
            get {
                return this.queue_timeoutField;
            }
            set {
                if ((this.queue_timeoutField.Equals(value) != true)) {
                    this.queue_timeoutField = value;
                    this.RaisePropertyChanged("queue_timeout");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ring_duration {
            get {
                return this.ring_durationField;
            }
            set {
                if ((this.ring_durationField.Equals(value) != true)) {
                    this.ring_durationField = value;
                    this.RaisePropertyChanged("ring_duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ringinuse {
            get {
                return this.ringinuseField;
            }
            set {
                if ((this.ringinuseField.Equals(value) != true)) {
                    this.ringinuseField = value;
                    this.RaisePropertyChanged("ringinuse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool user_agent_priority {
            get {
                return this.user_agent_priorityField;
            }
            set {
                if ((this.user_agent_priorityField.Equals(value) != true)) {
                    this.user_agent_priorityField = value;
                    this.RaisePropertyChanged("user_agent_priority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int wrapup_time {
            get {
                return this.wrapup_timeField;
            }
            set {
                if ((this.wrapup_timeField.Equals(value) != true)) {
                    this.wrapup_timeField = value;
                    this.RaisePropertyChanged("wrapup_time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool zero_exits_queue {
            get {
                return this.zero_exits_queueField;
            }
            set {
                if ((this.zero_exits_queueField.Equals(value) != true)) {
                    this.zero_exits_queueField = value;
                    this.RaisePropertyChanged("zero_exits_queue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="queue.agent_removal_actions", Namespace="http://schemas.datacontract.org/2004/07/pbx_shared")]
        public enum agent_removal_actions : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            pause = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            logoff = 1,
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="queue.unanswered_actions", Namespace="http://schemas.datacontract.org/2004/07/pbx_shared")]
        public enum unanswered_actions : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            do_nothing = 0,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="supportrep", Namespace="http://schemas.datacontract.org/2004/07/pbx_shared")]
    [System.SerializableAttribute()]
    public partial class supportrep : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private test_pbx_web2.LIVE_adminproxy.phonecall activecallField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string repidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private test_pbx_web2.LIVE_adminproxy.supportrep.repstates repstateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime returntoavailabletimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool standbyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public test_pbx_web2.LIVE_adminproxy.phonecall activecall {
            get {
                return this.activecallField;
            }
            set {
                if ((object.ReferenceEquals(this.activecallField, value) != true)) {
                    this.activecallField = value;
                    this.RaisePropertyChanged("activecall");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string repid {
            get {
                return this.repidField;
            }
            set {
                if ((object.ReferenceEquals(this.repidField, value) != true)) {
                    this.repidField = value;
                    this.RaisePropertyChanged("repid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public test_pbx_web2.LIVE_adminproxy.supportrep.repstates repstate {
            get {
                return this.repstateField;
            }
            set {
                if ((this.repstateField.Equals(value) != true)) {
                    this.repstateField = value;
                    this.RaisePropertyChanged("repstate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime returntoavailabletime {
            get {
                return this.returntoavailabletimeField;
            }
            set {
                if ((this.returntoavailabletimeField.Equals(value) != true)) {
                    this.returntoavailabletimeField = value;
                    this.RaisePropertyChanged("returntoavailabletime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool standby {
            get {
                return this.standbyField;
            }
            set {
                if ((this.standbyField.Equals(value) != true)) {
                    this.standbyField = value;
                    this.RaisePropertyChanged("standby");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="supportrep.repstates", Namespace="http://schemas.datacontract.org/2004/07/pbx_shared")]
        public enum repstates : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            offduty = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            available = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            inacall = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            postcallcleanup = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            unavailable = 4,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="phonecall", Namespace="http://schemas.datacontract.org/2004/07/pbx_shared")]
    [System.SerializableAttribute()]
    public partial class phonecall : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private test_pbx_web2.LIVE_adminproxy.phonecall.callstates callstateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private test_pbx_web2.LIVE_adminproxy.extension[] connected_extensionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dialednbrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private test_pbx_web2.LIVE_adminproxy.phonecall.calldirection directionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime endtimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime initiallyansweredatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string localnbrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int phonesystemcallidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string remotenbrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime starttimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int switchidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int switchspecificcallidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int totalholdmsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public test_pbx_web2.LIVE_adminproxy.phonecall.callstates callstate {
            get {
                return this.callstateField;
            }
            set {
                if ((this.callstateField.Equals(value) != true)) {
                    this.callstateField = value;
                    this.RaisePropertyChanged("callstate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public test_pbx_web2.LIVE_adminproxy.extension[] connected_extensions {
            get {
                return this.connected_extensionsField;
            }
            set {
                if ((object.ReferenceEquals(this.connected_extensionsField, value) != true)) {
                    this.connected_extensionsField = value;
                    this.RaisePropertyChanged("connected_extensions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dialednbr {
            get {
                return this.dialednbrField;
            }
            set {
                if ((object.ReferenceEquals(this.dialednbrField, value) != true)) {
                    this.dialednbrField = value;
                    this.RaisePropertyChanged("dialednbr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public test_pbx_web2.LIVE_adminproxy.phonecall.calldirection direction {
            get {
                return this.directionField;
            }
            set {
                if ((this.directionField.Equals(value) != true)) {
                    this.directionField = value;
                    this.RaisePropertyChanged("direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime endtime {
            get {
                return this.endtimeField;
            }
            set {
                if ((this.endtimeField.Equals(value) != true)) {
                    this.endtimeField = value;
                    this.RaisePropertyChanged("endtime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime initiallyansweredat {
            get {
                return this.initiallyansweredatField;
            }
            set {
                if ((this.initiallyansweredatField.Equals(value) != true)) {
                    this.initiallyansweredatField = value;
                    this.RaisePropertyChanged("initiallyansweredat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string localnbr {
            get {
                return this.localnbrField;
            }
            set {
                if ((object.ReferenceEquals(this.localnbrField, value) != true)) {
                    this.localnbrField = value;
                    this.RaisePropertyChanged("localnbr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int phonesystemcallid {
            get {
                return this.phonesystemcallidField;
            }
            set {
                if ((this.phonesystemcallidField.Equals(value) != true)) {
                    this.phonesystemcallidField = value;
                    this.RaisePropertyChanged("phonesystemcallid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string remotenbr {
            get {
                return this.remotenbrField;
            }
            set {
                if ((object.ReferenceEquals(this.remotenbrField, value) != true)) {
                    this.remotenbrField = value;
                    this.RaisePropertyChanged("remotenbr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime starttime {
            get {
                return this.starttimeField;
            }
            set {
                if ((this.starttimeField.Equals(value) != true)) {
                    this.starttimeField = value;
                    this.RaisePropertyChanged("starttime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int switchid {
            get {
                return this.switchidField;
            }
            set {
                if ((this.switchidField.Equals(value) != true)) {
                    this.switchidField = value;
                    this.RaisePropertyChanged("switchid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int switchspecificcallid {
            get {
                return this.switchspecificcallidField;
            }
            set {
                if ((this.switchspecificcallidField.Equals(value) != true)) {
                    this.switchspecificcallidField = value;
                    this.RaisePropertyChanged("switchspecificcallid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int totalholdms {
            get {
                return this.totalholdmsField;
            }
            set {
                if ((this.totalholdmsField.Equals(value) != true)) {
                    this.totalholdmsField = value;
                    this.RaisePropertyChanged("totalholdms");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="phonecall.callstates", Namespace="http://schemas.datacontract.org/2004/07/pbx_shared")]
        public enum callstates : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ringing = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            hold = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            active = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ended = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            unknown = 4,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ringing_again = 5,
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="phonecall.calldirection", Namespace="http://schemas.datacontract.org/2004/07/pbx_shared")]
        public enum calldirection : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            inbound = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            outbound = 1,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultBase", Namespace="http://schemas.datacontract.org/2004/07/pbx_web.wcf")]
    [System.SerializableAttribute()]
    public partial class FaultBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int excodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int excode {
            get {
                return this.excodeField;
            }
            set {
                if ((this.excodeField.Equals(value) != true)) {
                    this.excodeField = value;
                    this.RaisePropertyChanged("excode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LIVE_adminproxy.IPhoneSwitchAdminService")]
    public interface IPhoneSwitchAdminService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneSwitchAdminService/getphonenumbers", ReplyAction="http://tempuri.org/IPhoneSwitchAdminService/getphonenumbersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(test_pbx_web2.LIVE_adminproxy.FaultBase), Action="http://tempuri.org/IPhoneSwitchAdminService/getphonenumbersFaultBaseFault", Name="FaultBase", Namespace="http://schemas.datacontract.org/2004/07/pbx_web.wcf")]
        test_pbx_web2.LIVE_adminproxy.phonenumber[] getphonenumbers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneSwitchAdminService/getphonenumbers", ReplyAction="http://tempuri.org/IPhoneSwitchAdminService/getphonenumbersResponse")]
        System.Threading.Tasks.Task<test_pbx_web2.LIVE_adminproxy.phonenumber[]> getphonenumbersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPhoneSwitchAdminServiceChannel : test_pbx_web2.LIVE_adminproxy.IPhoneSwitchAdminService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PhoneSwitchAdminServiceClient : System.ServiceModel.ClientBase<test_pbx_web2.LIVE_adminproxy.IPhoneSwitchAdminService>, test_pbx_web2.LIVE_adminproxy.IPhoneSwitchAdminService {
        
        public PhoneSwitchAdminServiceClient() {
        }
        
        public PhoneSwitchAdminServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PhoneSwitchAdminServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhoneSwitchAdminServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhoneSwitchAdminServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public test_pbx_web2.LIVE_adminproxy.phonenumber[] getphonenumbers() {
            return base.Channel.getphonenumbers();
        }
        
        public System.Threading.Tasks.Task<test_pbx_web2.LIVE_adminproxy.phonenumber[]> getphonenumbersAsync() {
            return base.Channel.getphonenumbersAsync();
        }
    }
}
