//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_pbx_web2.LIVE_publicapiproxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultBase", Namespace="http://schemas.datacontract.org/2004/07/pbx_web.wcf")]
    [System.SerializableAttribute()]
    public partial class FaultBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int excodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int excode {
            get {
                return this.excodeField;
            }
            set {
                if ((this.excodeField.Equals(value) != true)) {
                    this.excodeField = value;
                    this.RaisePropertyChanged("excode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="newcallinfo", Namespace="http://schemas.datacontract.org/2004/07/pbx_shared.misc")]
    [System.SerializableAttribute()]
    public partial class newcallinfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dialednumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string localnumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string remotenumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dialednumber {
            get {
                return this.dialednumberField;
            }
            set {
                if ((object.ReferenceEquals(this.dialednumberField, value) != true)) {
                    this.dialednumberField = value;
                    this.RaisePropertyChanged("dialednumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string localnumber {
            get {
                return this.localnumberField;
            }
            set {
                if ((object.ReferenceEquals(this.localnumberField, value) != true)) {
                    this.localnumberField = value;
                    this.RaisePropertyChanged("localnumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string remotenumber {
            get {
                return this.remotenumberField;
            }
            set {
                if ((object.ReferenceEquals(this.remotenumberField, value) != true)) {
                    this.remotenumberField = value;
                    this.RaisePropertyChanged("remotenumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="phonecall", Namespace="http://schemas.datacontract.org/2004/07/pbx_shared")]
    [System.SerializableAttribute()]
    public partial class phonecall : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private test_pbx_web2.LIVE_publicapiproxy.phonecall.callstates callstateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private test_pbx_web2.LIVE_publicapiproxy.extension[] connected_extensionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dialednbrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private test_pbx_web2.LIVE_publicapiproxy.phonecall.calldirection directionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime endtimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime initiallyansweredatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string localnbrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int phonesystemcallidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string remotenbrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime starttimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int switchidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int switchspecificcallidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int totalholdmsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public test_pbx_web2.LIVE_publicapiproxy.phonecall.callstates callstate {
            get {
                return this.callstateField;
            }
            set {
                if ((this.callstateField.Equals(value) != true)) {
                    this.callstateField = value;
                    this.RaisePropertyChanged("callstate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public test_pbx_web2.LIVE_publicapiproxy.extension[] connected_extensions {
            get {
                return this.connected_extensionsField;
            }
            set {
                if ((object.ReferenceEquals(this.connected_extensionsField, value) != true)) {
                    this.connected_extensionsField = value;
                    this.RaisePropertyChanged("connected_extensions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dialednbr {
            get {
                return this.dialednbrField;
            }
            set {
                if ((object.ReferenceEquals(this.dialednbrField, value) != true)) {
                    this.dialednbrField = value;
                    this.RaisePropertyChanged("dialednbr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public test_pbx_web2.LIVE_publicapiproxy.phonecall.calldirection direction {
            get {
                return this.directionField;
            }
            set {
                if ((this.directionField.Equals(value) != true)) {
                    this.directionField = value;
                    this.RaisePropertyChanged("direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime endtime {
            get {
                return this.endtimeField;
            }
            set {
                if ((this.endtimeField.Equals(value) != true)) {
                    this.endtimeField = value;
                    this.RaisePropertyChanged("endtime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime initiallyansweredat {
            get {
                return this.initiallyansweredatField;
            }
            set {
                if ((this.initiallyansweredatField.Equals(value) != true)) {
                    this.initiallyansweredatField = value;
                    this.RaisePropertyChanged("initiallyansweredat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string localnbr {
            get {
                return this.localnbrField;
            }
            set {
                if ((object.ReferenceEquals(this.localnbrField, value) != true)) {
                    this.localnbrField = value;
                    this.RaisePropertyChanged("localnbr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int phonesystemcallid {
            get {
                return this.phonesystemcallidField;
            }
            set {
                if ((this.phonesystemcallidField.Equals(value) != true)) {
                    this.phonesystemcallidField = value;
                    this.RaisePropertyChanged("phonesystemcallid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string remotenbr {
            get {
                return this.remotenbrField;
            }
            set {
                if ((object.ReferenceEquals(this.remotenbrField, value) != true)) {
                    this.remotenbrField = value;
                    this.RaisePropertyChanged("remotenbr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime starttime {
            get {
                return this.starttimeField;
            }
            set {
                if ((this.starttimeField.Equals(value) != true)) {
                    this.starttimeField = value;
                    this.RaisePropertyChanged("starttime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int switchid {
            get {
                return this.switchidField;
            }
            set {
                if ((this.switchidField.Equals(value) != true)) {
                    this.switchidField = value;
                    this.RaisePropertyChanged("switchid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int switchspecificcallid {
            get {
                return this.switchspecificcallidField;
            }
            set {
                if ((this.switchspecificcallidField.Equals(value) != true)) {
                    this.switchspecificcallidField = value;
                    this.RaisePropertyChanged("switchspecificcallid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int totalholdms {
            get {
                return this.totalholdmsField;
            }
            set {
                if ((this.totalholdmsField.Equals(value) != true)) {
                    this.totalholdmsField = value;
                    this.RaisePropertyChanged("totalholdms");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="phonecall.callstates", Namespace="http://schemas.datacontract.org/2004/07/pbx_shared")]
        public enum callstates : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ringing = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            hold = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            active = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ended = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            unknown = 4,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ringing_again = 5,
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="phonecall.calldirection", Namespace="http://schemas.datacontract.org/2004/07/pbx_shared")]
        public enum calldirection : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            inbound = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            outbound = 1,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="extension", Namespace="http://schemas.datacontract.org/2004/07/pbx_shared")]
    [System.SerializableAttribute()]
    public partial class extension : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string e911locationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string extension_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string extension_nbrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private test_pbx_web2.LIVE_publicapiproxy.extension.extension_types extension_typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string outbound_callerid_phonenbrField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string e911location {
            get {
                return this.e911locationField;
            }
            set {
                if ((object.ReferenceEquals(this.e911locationField, value) != true)) {
                    this.e911locationField = value;
                    this.RaisePropertyChanged("e911location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string extension_name {
            get {
                return this.extension_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.extension_nameField, value) != true)) {
                    this.extension_nameField = value;
                    this.RaisePropertyChanged("extension_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string extension_nbr {
            get {
                return this.extension_nbrField;
            }
            set {
                if ((object.ReferenceEquals(this.extension_nbrField, value) != true)) {
                    this.extension_nbrField = value;
                    this.RaisePropertyChanged("extension_nbr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public test_pbx_web2.LIVE_publicapiproxy.extension.extension_types extension_type {
            get {
                return this.extension_typeField;
            }
            set {
                if ((this.extension_typeField.Equals(value) != true)) {
                    this.extension_typeField = value;
                    this.RaisePropertyChanged("extension_type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string outbound_callerid_phonenbr {
            get {
                return this.outbound_callerid_phonenbrField;
            }
            set {
                if ((object.ReferenceEquals(this.outbound_callerid_phonenbrField, value) != true)) {
                    this.outbound_callerid_phonenbrField = value;
                    this.RaisePropertyChanged("outbound_callerid_phonenbr");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="extension.extension_types", Namespace="http://schemas.datacontract.org/2004/07/pbx_shared")]
        public enum extension_types : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            digital = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ip = 1,
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LIVE_publicapiproxy.IPhoneSwitchPublicAPIService")]
    public interface IPhoneSwitchPublicAPIService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneSwitchPublicAPIService/endcall", ReplyAction="http://tempuri.org/IPhoneSwitchPublicAPIService/endcallResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(test_pbx_web2.LIVE_publicapiproxy.FaultBase), Action="http://tempuri.org/IPhoneSwitchPublicAPIService/endcallFaultBaseFault", Name="FaultBase", Namespace="http://schemas.datacontract.org/2004/07/pbx_web.wcf")]
        void endcall(int callid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneSwitchPublicAPIService/endcall", ReplyAction="http://tempuri.org/IPhoneSwitchPublicAPIService/endcallResponse")]
        System.Threading.Tasks.Task endcallAsync(int callid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneSwitchPublicAPIService/newcall", ReplyAction="http://tempuri.org/IPhoneSwitchPublicAPIService/newcallResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(test_pbx_web2.LIVE_publicapiproxy.FaultBase), Action="http://tempuri.org/IPhoneSwitchPublicAPIService/newcallFaultBaseFault", Name="FaultBase", Namespace="http://schemas.datacontract.org/2004/07/pbx_web.wcf")]
        test_pbx_web2.LIVE_publicapiproxy.phonecall newcall(test_pbx_web2.LIVE_publicapiproxy.newcallinfo calldetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneSwitchPublicAPIService/newcall", ReplyAction="http://tempuri.org/IPhoneSwitchPublicAPIService/newcallResponse")]
        System.Threading.Tasks.Task<test_pbx_web2.LIVE_publicapiproxy.phonecall> newcallAsync(test_pbx_web2.LIVE_publicapiproxy.newcallinfo calldetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneSwitchPublicAPIService/connect_extension", ReplyAction="http://tempuri.org/IPhoneSwitchPublicAPIService/connect_extensionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(test_pbx_web2.LIVE_publicapiproxy.FaultBase), Action="http://tempuri.org/IPhoneSwitchPublicAPIService/connect_extensionFaultBaseFault", Name="FaultBase", Namespace="http://schemas.datacontract.org/2004/07/pbx_web.wcf")]
        void connect_extension(int callid, string extension_nbr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneSwitchPublicAPIService/connect_extension", ReplyAction="http://tempuri.org/IPhoneSwitchPublicAPIService/connect_extensionResponse")]
        System.Threading.Tasks.Task connect_extensionAsync(int callid, string extension_nbr);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPhoneSwitchPublicAPIServiceChannel : test_pbx_web2.LIVE_publicapiproxy.IPhoneSwitchPublicAPIService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PhoneSwitchPublicAPIServiceClient : System.ServiceModel.ClientBase<test_pbx_web2.LIVE_publicapiproxy.IPhoneSwitchPublicAPIService>, test_pbx_web2.LIVE_publicapiproxy.IPhoneSwitchPublicAPIService {
        
        public PhoneSwitchPublicAPIServiceClient() {
        }
        
        public PhoneSwitchPublicAPIServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PhoneSwitchPublicAPIServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhoneSwitchPublicAPIServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhoneSwitchPublicAPIServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void endcall(int callid) {
            base.Channel.endcall(callid);
        }
        
        public System.Threading.Tasks.Task endcallAsync(int callid) {
            return base.Channel.endcallAsync(callid);
        }
        
        public test_pbx_web2.LIVE_publicapiproxy.phonecall newcall(test_pbx_web2.LIVE_publicapiproxy.newcallinfo calldetails) {
            return base.Channel.newcall(calldetails);
        }
        
        public System.Threading.Tasks.Task<test_pbx_web2.LIVE_publicapiproxy.phonecall> newcallAsync(test_pbx_web2.LIVE_publicapiproxy.newcallinfo calldetails) {
            return base.Channel.newcallAsync(calldetails);
        }
        
        public void connect_extension(int callid, string extension_nbr) {
            base.Channel.connect_extension(callid, extension_nbr);
        }
        
        public System.Threading.Tasks.Task connect_extensionAsync(int callid, string extension_nbr) {
            return base.Channel.connect_extensionAsync(callid, extension_nbr);
        }
    }
}
