//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_pbx_web2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>1234567890,t1</string>
  <string>1234567891,t1</string>
  <string>1234567892,t1</string>
  <string>1234567893,t1</string>
  <string>1234567894,t1</string>
  <string>1234567895,t1</string>
  <string>1234567896,t1</string>
  <string>6175551234,analog</string>
  <string>6175551235,analog</string>
  <string>6175551236,analog</string>
  <string>6175551237,analog</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection pbx_trunks {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["pbx_trunks"]));
            }
            set {
                this["pbx_trunks"] = value;
            }
        }
    }
}
